[package]
name = "bootloader-loader"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bootloader-loader"
test = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tock-registers = "0.8.1"
