[package]
name = "rpi-os"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[[bin]]
name = "kernel"
path = "src/kernel/main.rs"

[dependencies]
aarch64-cpu = "*"
qemu-exit = "*"
tock-registers = "*"
