[build]
target = "aarch64-unknown-none-softfloat"
rustflags = [
   "-Ccode-model=tiny",
   "-Clink-args=-O3 --optimize-bb-jumps --demangle",
   "-Ctarget-cpu=cortex-a72",
   "-Cforce-frame-pointers=false",
   "-Cforce-unwind-tables=false",
   "-Clinker-plugin-lto=true",
]

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"
codegen-units = 128
panic = "abort"
strip = true
