[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies.quote]
version = "1.0.33"
default-features = false

[dependencies.syn]
version = "2.0.41"
default-features = false
features = ["derive", "parsing", "printing", "proc-macro"]