[package]
name = "user"
version = "0.1.0"
edition = "2021"

[dependencies]
bitfield-struct = "0.5.6"
macros = { path = "../macros" }
num-derive = { version = "0.4.1", default-features = false }
num-traits = { version = "0.2.17", default-features = false }
os = { path = "../os" }
